name: Releases

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python: ["3.9"]
        arch: ["x86"]

    steps:
      - name: Checkout lupa
        uses: actions/checkout@v2
        with:
          repository: "scoder/lupa"
          path: "lupa"

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.arch }}

      - name: Setup msvc ${{ matrix.arch }}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Build LuaJIT
        run: |
          Invoke-WebRequest http://luajit.org/download/LuaJIT-2.1.0-beta3.tar.gz -OutFile luajit.tar.gz
          tar -xvzf luajit.tar.gz
          cd LuaJIT-2.1.0-beta3/src
          ./msvcbuild.bat

      - name: Build lupa wheel
        run: |
          cd lupa
          pip install -U pip
          pip install -U Cython setuptools wheel
          python setup.py bdist_wheel --lua-includes ../LuaJIT-2.1.0-beta3/src --lua-lib ../LuaJIT-2.1.0-beta3/src/lua51.lib

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ matrix.python }}-${{ matrix.arch }}
          commit: main
          artifacts: "lupa/dist/*"
          body: "Build with: python${{ matrix.python }}, ${{ matrix.arch }}"
          token: ${{ secrets.GITHUB_TOKEN }}
