name: Releases

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9"]
        arch: ["x86", "x64"]

    steps:
      - uses: actions/checkout@v2

      - name: Checkout lupa
        uses: actions/checkout@v2
        with:
          repository: "scoder/lupa"
          path: "lupa"

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Download LuaJIT
        run: |
          Invoke-WebRequest http://luajit.org/download/LuaJIT-2.1.0-beta3.tar.gz -OutFile luajit.tar.gz
          tar -xvzf luajit.tar.gz

      - name: Prepare LuaJIT
        run: |
          python update_target.py ${{ matrix.arch }}

      - name: Setup msvc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: "x64"

      - name: Build LuaJIT
        run: |
          cd LuaJIT-2.1.0-beta3/src
          ./msvcbuild.bat

      - name: Test LuaJIT
        run: |
          ./LuaJIT-2.1.0-beta3/src/luajit.exe test-${{ matrix.arch }}.lua

      - name: Prepare python
        run: |
          pip install -U pip
          pip install -U Cython setuptools wheel

      - name: Test lupa
        run: |
          cd lupa
          python setup.py install --lua-includes ../LuaJIT-2.1.0-beta3/src --lua-lib ../LuaJIT-2.1.0-beta3/src/lua51.lib
          cd ..
          python test.py ${{ matrix.arch }}

      - name: Build lupa wheel
        run: |
          cd lupa
          python setup.py bdist_wheel --lua-includes ../LuaJIT-2.1.0-beta3/src --lua-lib ../LuaJIT-2.1.0-beta3/src/lua51.lib

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: ${{ matrix.python }}-${{ matrix.arch }}
          commit: main
          artifacts: "lupa/dist/*"
          body: "Build with: python${{ matrix.python }}, ${{ matrix.arch }}"
          token: ${{ secrets.GITHUB_TOKEN }}
